sodu: required
services:
  - docker

before_install:
  - docker build -t nguyentuanbk92/docker-react -f Dockerfile.dev .

script:
  - docker run nguyentuanbk92/docker-react npm run test -- --coverage
